// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: spark_ssp_internal.proto

package spark_ssp_internal

import (
	context "context"
	spark "github.com/lightsparkdev/spark/proto/spark"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SparkSspInternalService_PrepareTreeAddress_FullMethodName                  = "/spark_ssp_internal.SparkSspInternalService/prepare_tree_address"
	SparkSspInternalService_CreateTree_FullMethodName                          = "/spark_ssp_internal.SparkSspInternalService/create_tree"
	SparkSspInternalService_InitiateCounterTransfer_FullMethodName             = "/spark_ssp_internal.SparkSspInternalService/initiate_counter_transfer"
	SparkSspInternalService_ReturnStuckTransfer_FullMethodName                 = "/spark_ssp_internal.SparkSspInternalService/return_stuck_transfer"
	SparkSspInternalService_InitiateStaticDepositUtxoSwap_FullMethodName       = "/spark_ssp_internal.SparkSspInternalService/initiate_static_deposit_utxo_swap"
	SparkSspInternalService_ReserveInstantStaticDepositUtxoSwap_FullMethodName = "/spark_ssp_internal.SparkSspInternalService/reserve_instant_static_deposit_utxo_swap"
	SparkSspInternalService_ClaimInstantStaticDepositUtxoSwap_FullMethodName   = "/spark_ssp_internal.SparkSspInternalService/claim_instant_static_deposit_utxo_swap"
	SparkSspInternalService_SignStaticDepositSweepTx_FullMethodName            = "/spark_ssp_internal.SparkSspInternalService/sign_static_deposit_sweep_tx"
)

// SparkSspInternalServiceClient is the client API for SparkSspInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The part of the operators' service provider API that Breez's service provider
// calls, under the names Lightspark's operators serve it by. The upstream
// definition of this service is not public.
type SparkSspInternalServiceClient interface {
	PrepareTreeAddress(ctx context.Context, in *spark.PrepareTreeAddressRequest, opts ...grpc.CallOption) (*spark.PrepareTreeAddressResponse, error)
	CreateTree(ctx context.Context, in *spark.CreateTreeRequest, opts ...grpc.CallOption) (*spark.CreateTreeResponse, error)
	InitiateCounterTransfer(ctx context.Context, in *CounterTransferRequest, opts ...grpc.CallOption) (*spark.StartTransferResponse, error)
	ReturnStuckTransfer(ctx context.Context, in *ReturnStuckTransferRequest, opts ...grpc.CallOption) (*ReturnStuckTransferResponse, error)
	InitiateStaticDepositUtxoSwap(ctx context.Context, in *InitiateStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*InitiateStaticDepositUtxoSwapResponse, error)
	ReserveInstantStaticDepositUtxoSwap(ctx context.Context, in *ReserveInstantStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*ReserveInstantStaticDepositUtxoSwapResponse, error)
	ClaimInstantStaticDepositUtxoSwap(ctx context.Context, in *ClaimInstantStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*ClaimInstantStaticDepositUtxoSwapResponse, error)
	SignStaticDepositSweepTx(ctx context.Context, in *SignStaticDepositSweepTxRequest, opts ...grpc.CallOption) (*SignStaticDepositSweepTxResponse, error)
}

type sparkSspInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSparkSspInternalServiceClient(cc grpc.ClientConnInterface) SparkSspInternalServiceClient {
	return &sparkSspInternalServiceClient{cc}
}

func (c *sparkSspInternalServiceClient) PrepareTreeAddress(ctx context.Context, in *spark.PrepareTreeAddressRequest, opts ...grpc.CallOption) (*spark.PrepareTreeAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.PrepareTreeAddressResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_PrepareTreeAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) CreateTree(ctx context.Context, in *spark.CreateTreeRequest, opts ...grpc.CallOption) (*spark.CreateTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.CreateTreeResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_CreateTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) InitiateCounterTransfer(ctx context.Context, in *CounterTransferRequest, opts ...grpc.CallOption) (*spark.StartTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(spark.StartTransferResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_InitiateCounterTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) ReturnStuckTransfer(ctx context.Context, in *ReturnStuckTransferRequest, opts ...grpc.CallOption) (*ReturnStuckTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnStuckTransferResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_ReturnStuckTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) InitiateStaticDepositUtxoSwap(ctx context.Context, in *InitiateStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*InitiateStaticDepositUtxoSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateStaticDepositUtxoSwapResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_InitiateStaticDepositUtxoSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) ReserveInstantStaticDepositUtxoSwap(ctx context.Context, in *ReserveInstantStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*ReserveInstantStaticDepositUtxoSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveInstantStaticDepositUtxoSwapResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_ReserveInstantStaticDepositUtxoSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) ClaimInstantStaticDepositUtxoSwap(ctx context.Context, in *ClaimInstantStaticDepositUtxoSwapRequest, opts ...grpc.CallOption) (*ClaimInstantStaticDepositUtxoSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimInstantStaticDepositUtxoSwapResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_ClaimInstantStaticDepositUtxoSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sparkSspInternalServiceClient) SignStaticDepositSweepTx(ctx context.Context, in *SignStaticDepositSweepTxRequest, opts ...grpc.CallOption) (*SignStaticDepositSweepTxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignStaticDepositSweepTxResponse)
	err := c.cc.Invoke(ctx, SparkSspInternalService_SignStaticDepositSweepTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SparkSspInternalServiceServer is the server API for SparkSspInternalService service.
// All implementations must embed UnimplementedSparkSspInternalServiceServer
// for forward compatibility.
//
// The part of the operators' service provider API that Breez's service provider
// calls, under the names Lightspark's operators serve it by. The upstream
// definition of this service is not public.
type SparkSspInternalServiceServer interface {
	PrepareTreeAddress(context.Context, *spark.PrepareTreeAddressRequest) (*spark.PrepareTreeAddressResponse, error)
	CreateTree(context.Context, *spark.CreateTreeRequest) (*spark.CreateTreeResponse, error)
	InitiateCounterTransfer(context.Context, *CounterTransferRequest) (*spark.StartTransferResponse, error)
	ReturnStuckTransfer(context.Context, *ReturnStuckTransferRequest) (*ReturnStuckTransferResponse, error)
	InitiateStaticDepositUtxoSwap(context.Context, *InitiateStaticDepositUtxoSwapRequest) (*InitiateStaticDepositUtxoSwapResponse, error)
	ReserveInstantStaticDepositUtxoSwap(context.Context, *ReserveInstantStaticDepositUtxoSwapRequest) (*ReserveInstantStaticDepositUtxoSwapResponse, error)
	ClaimInstantStaticDepositUtxoSwap(context.Context, *ClaimInstantStaticDepositUtxoSwapRequest) (*ClaimInstantStaticDepositUtxoSwapResponse, error)
	SignStaticDepositSweepTx(context.Context, *SignStaticDepositSweepTxRequest) (*SignStaticDepositSweepTxResponse, error)
	mustEmbedUnimplementedSparkSspInternalServiceServer()
}

// UnimplementedSparkSspInternalServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSparkSspInternalServiceServer struct{}

func (UnimplementedSparkSspInternalServiceServer) PrepareTreeAddress(context.Context, *spark.PrepareTreeAddressRequest) (*spark.PrepareTreeAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareTreeAddress not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) CreateTree(context.Context, *spark.CreateTreeRequest) (*spark.CreateTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTree not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) InitiateCounterTransfer(context.Context, *CounterTransferRequest) (*spark.StartTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateCounterTransfer not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) ReturnStuckTransfer(context.Context, *ReturnStuckTransferRequest) (*ReturnStuckTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReturnStuckTransfer not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) InitiateStaticDepositUtxoSwap(context.Context, *InitiateStaticDepositUtxoSwapRequest) (*InitiateStaticDepositUtxoSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateStaticDepositUtxoSwap not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) ReserveInstantStaticDepositUtxoSwap(context.Context, *ReserveInstantStaticDepositUtxoSwapRequest) (*ReserveInstantStaticDepositUtxoSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveInstantStaticDepositUtxoSwap not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) ClaimInstantStaticDepositUtxoSwap(context.Context, *ClaimInstantStaticDepositUtxoSwapRequest) (*ClaimInstantStaticDepositUtxoSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimInstantStaticDepositUtxoSwap not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) SignStaticDepositSweepTx(context.Context, *SignStaticDepositSweepTxRequest) (*SignStaticDepositSweepTxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignStaticDepositSweepTx not implemented")
}
func (UnimplementedSparkSspInternalServiceServer) mustEmbedUnimplementedSparkSspInternalServiceServer() {
}
func (UnimplementedSparkSspInternalServiceServer) testEmbeddedByValue() {}

// UnsafeSparkSspInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SparkSspInternalServiceServer will
// result in compilation errors.
type UnsafeSparkSspInternalServiceServer interface {
	mustEmbedUnimplementedSparkSspInternalServiceServer()
}

func RegisterSparkSspInternalServiceServer(s grpc.ServiceRegistrar, srv SparkSspInternalServiceServer) {
	// If the following call panics, it indicates UnimplementedSparkSspInternalServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SparkSspInternalService_ServiceDesc, srv)
}

func _SparkSspInternalService_PrepareTreeAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.PrepareTreeAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).PrepareTreeAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_PrepareTreeAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).PrepareTreeAddress(ctx, req.(*spark.PrepareTreeAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_CreateTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(spark.CreateTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).CreateTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_CreateTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).CreateTree(ctx, req.(*spark.CreateTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_InitiateCounterTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).InitiateCounterTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_InitiateCounterTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).InitiateCounterTransfer(ctx, req.(*CounterTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_ReturnStuckTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnStuckTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).ReturnStuckTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_ReturnStuckTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).ReturnStuckTransfer(ctx, req.(*ReturnStuckTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_InitiateStaticDepositUtxoSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateStaticDepositUtxoSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).InitiateStaticDepositUtxoSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_InitiateStaticDepositUtxoSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).InitiateStaticDepositUtxoSwap(ctx, req.(*InitiateStaticDepositUtxoSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_ReserveInstantStaticDepositUtxoSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveInstantStaticDepositUtxoSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).ReserveInstantStaticDepositUtxoSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_ReserveInstantStaticDepositUtxoSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).ReserveInstantStaticDepositUtxoSwap(ctx, req.(*ReserveInstantStaticDepositUtxoSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_ClaimInstantStaticDepositUtxoSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimInstantStaticDepositUtxoSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).ClaimInstantStaticDepositUtxoSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_ClaimInstantStaticDepositUtxoSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).ClaimInstantStaticDepositUtxoSwap(ctx, req.(*ClaimInstantStaticDepositUtxoSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SparkSspInternalService_SignStaticDepositSweepTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignStaticDepositSweepTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SparkSspInternalServiceServer).SignStaticDepositSweepTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SparkSspInternalService_SignStaticDepositSweepTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SparkSspInternalServiceServer).SignStaticDepositSweepTx(ctx, req.(*SignStaticDepositSweepTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SparkSspInternalService_ServiceDesc is the grpc.ServiceDesc for SparkSspInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SparkSspInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spark_ssp_internal.SparkSspInternalService",
	HandlerType: (*SparkSspInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "prepare_tree_address",
			Handler:    _SparkSspInternalService_PrepareTreeAddress_Handler,
		},
		{
			MethodName: "create_tree",
			Handler:    _SparkSspInternalService_CreateTree_Handler,
		},
		{
			MethodName: "initiate_counter_transfer",
			Handler:    _SparkSspInternalService_InitiateCounterTransfer_Handler,
		},
		{
			MethodName: "return_stuck_transfer",
			Handler:    _SparkSspInternalService_ReturnStuckTransfer_Handler,
		},
		{
			MethodName: "initiate_static_deposit_utxo_swap",
			Handler:    _SparkSspInternalService_InitiateStaticDepositUtxoSwap_Handler,
		},
		{
			MethodName: "reserve_instant_static_deposit_utxo_swap",
			Handler:    _SparkSspInternalService_ReserveInstantStaticDepositUtxoSwap_Handler,
		},
		{
			MethodName: "claim_instant_static_deposit_utxo_swap",
			Handler:    _SparkSspInternalService_ClaimInstantStaticDepositUtxoSwap_Handler,
		},
		{
			MethodName: "sign_static_deposit_sweep_tx",
			Handler:    _SparkSspInternalService_SignStaticDepositSweepTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spark_ssp_internal.proto",
}
