// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: spark_ssp_internal.proto

package spark_ssp_internal

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	common "github.com/lightsparkdev/spark/proto/common"
	spark "github.com/lightsparkdev/spark/proto/spark"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SweepIneligibleReason int32

const (
	SweepIneligibleReason_SWEEP_INELIGIBLE_REASON_UNSPECIFIED         SweepIneligibleReason = 0
	SweepIneligibleReason_SWEEP_INELIGIBLE_REASON_UNKNOWN_UTXO        SweepIneligibleReason = 1
	SweepIneligibleReason_SWEEP_INELIGIBLE_REASON_NO_SWAP             SweepIneligibleReason = 2
	SweepIneligibleReason_SWEEP_INELIGIBLE_REASON_SWAP_NOT_COMPLETED  SweepIneligibleReason = 3
	SweepIneligibleReason_SWEEP_INELIGIBLE_REASON_NOT_OWNED_BY_CALLER SweepIneligibleReason = 4
	SweepIneligibleReason_SWEEP_INELIGIBLE_REASON_REFUND_SWAP         SweepIneligibleReason = 5
)

// Enum value maps for SweepIneligibleReason.
var (
	SweepIneligibleReason_name = map[int32]string{
		0: "SWEEP_INELIGIBLE_REASON_UNSPECIFIED",
		1: "SWEEP_INELIGIBLE_REASON_UNKNOWN_UTXO",
		2: "SWEEP_INELIGIBLE_REASON_NO_SWAP",
		3: "SWEEP_INELIGIBLE_REASON_SWAP_NOT_COMPLETED",
		4: "SWEEP_INELIGIBLE_REASON_NOT_OWNED_BY_CALLER",
		5: "SWEEP_INELIGIBLE_REASON_REFUND_SWAP",
	}
	SweepIneligibleReason_value = map[string]int32{
		"SWEEP_INELIGIBLE_REASON_UNSPECIFIED":         0,
		"SWEEP_INELIGIBLE_REASON_UNKNOWN_UTXO":        1,
		"SWEEP_INELIGIBLE_REASON_NO_SWAP":             2,
		"SWEEP_INELIGIBLE_REASON_SWAP_NOT_COMPLETED":  3,
		"SWEEP_INELIGIBLE_REASON_NOT_OWNED_BY_CALLER": 4,
		"SWEEP_INELIGIBLE_REASON_REFUND_SWAP":         5,
	}
)

func (x SweepIneligibleReason) Enum() *SweepIneligibleReason {
	p := new(SweepIneligibleReason)
	*p = x
	return p
}

func (x SweepIneligibleReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SweepIneligibleReason) Descriptor() protoreflect.EnumDescriptor {
	return file_spark_ssp_internal_proto_enumTypes[0].Descriptor()
}

func (SweepIneligibleReason) Type() protoreflect.EnumType {
	return &file_spark_ssp_internal_proto_enumTypes[0]
}

func (x SweepIneligibleReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SweepIneligibleReason.Descriptor instead.
func (SweepIneligibleReason) EnumDescriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{0}
}

type InitiateStaticDepositUtxoSwapRequest struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	OnChainUtxo       *spark.UTXO                 `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	SspSignature      []byte                      `protobuf:"bytes,2,opt,name=ssp_signature,json=sspSignature,proto3" json:"ssp_signature,omitempty"`
	UserSignature     []byte                      `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	Transfer          *spark.StartTransferRequest `protobuf:"bytes,4,opt,name=transfer,proto3" json:"transfer,omitempty"`
	SpendTxSigningJob *spark.SigningJob           `protobuf:"bytes,5,opt,name=spend_tx_signing_job,json=spendTxSigningJob,proto3" json:"spend_tx_signing_job,omitempty"`
	HashVariant       spark.HashVariant           `protobuf:"varint,6,opt,name=hash_variant,json=hashVariant,proto3,enum=spark.HashVariant" json:"hash_variant,omitempty"`
	// Unset uses the network's default.
	ConfirmationThreshold *uint32 `protobuf:"varint,7,opt,name=confirmation_threshold,json=confirmationThreshold,proto3,oneof" json:"confirmation_threshold,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InitiateStaticDepositUtxoSwapRequest) Reset() {
	*x = InitiateStaticDepositUtxoSwapRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateStaticDepositUtxoSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateStaticDepositUtxoSwapRequest) ProtoMessage() {}

func (x *InitiateStaticDepositUtxoSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateStaticDepositUtxoSwapRequest.ProtoReflect.Descriptor instead.
func (*InitiateStaticDepositUtxoSwapRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateStaticDepositUtxoSwapRequest) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *InitiateStaticDepositUtxoSwapRequest) GetSspSignature() []byte {
	if x != nil {
		return x.SspSignature
	}
	return nil
}

func (x *InitiateStaticDepositUtxoSwapRequest) GetUserSignature() []byte {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *InitiateStaticDepositUtxoSwapRequest) GetTransfer() *spark.StartTransferRequest {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *InitiateStaticDepositUtxoSwapRequest) GetSpendTxSigningJob() *spark.SigningJob {
	if x != nil {
		return x.SpendTxSigningJob
	}
	return nil
}

func (x *InitiateStaticDepositUtxoSwapRequest) GetHashVariant() spark.HashVariant {
	if x != nil {
		return x.HashVariant
	}
	return spark.HashVariant(0)
}

func (x *InitiateStaticDepositUtxoSwapRequest) GetConfirmationThreshold() uint32 {
	if x != nil && x.ConfirmationThreshold != nil {
		return *x.ConfirmationThreshold
	}
	return 0
}

type InitiateStaticDepositUtxoSwapResponse struct {
	state                protoimpl.MessageState           `protogen:"open.v1"`
	SpendTxSigningResult *spark.SigningResult             `protobuf:"bytes,1,opt,name=spend_tx_signing_result,json=spendTxSigningResult,proto3" json:"spend_tx_signing_result,omitempty"`
	Transfer             *spark.Transfer                  `protobuf:"bytes,2,opt,name=transfer,proto3" json:"transfer,omitempty"`
	DepositAddress       *spark.DepositAddressQueryResult `protobuf:"bytes,3,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InitiateStaticDepositUtxoSwapResponse) Reset() {
	*x = InitiateStaticDepositUtxoSwapResponse{}
	mi := &file_spark_ssp_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateStaticDepositUtxoSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateStaticDepositUtxoSwapResponse) ProtoMessage() {}

func (x *InitiateStaticDepositUtxoSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateStaticDepositUtxoSwapResponse.ProtoReflect.Descriptor instead.
func (*InitiateStaticDepositUtxoSwapResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateStaticDepositUtxoSwapResponse) GetSpendTxSigningResult() *spark.SigningResult {
	if x != nil {
		return x.SpendTxSigningResult
	}
	return nil
}

func (x *InitiateStaticDepositUtxoSwapResponse) GetTransfer() *spark.Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *InitiateStaticDepositUtxoSwapResponse) GetDepositAddress() *spark.DepositAddressQueryResult {
	if x != nil {
		return x.DepositAddress
	}
	return nil
}

type CounterTransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Counter transfer with refunds and key tweaks signed.
	Transfer *spark.StartTransferRequest `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// Adaptor public keys to verify the signatures of refunds for the counter
	// transfer in the swap.
	AdaptorPublicKeys *spark.AdaptorPublicKeyPackage `protobuf:"bytes,2,opt,name=adaptor_public_keys,json=adaptorPublicKeys,proto3" json:"adaptor_public_keys,omitempty"`
	// The primary swap transfer this counter transfer settles against.
	PrimaryTransferId string `protobuf:"bytes,3,opt,name=primary_transfer_id,json=primaryTransferId,proto3" json:"primary_transfer_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CounterTransferRequest) Reset() {
	*x = CounterTransferRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterTransferRequest) ProtoMessage() {}

func (x *CounterTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterTransferRequest.ProtoReflect.Descriptor instead.
func (*CounterTransferRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{2}
}

func (x *CounterTransferRequest) GetTransfer() *spark.StartTransferRequest {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *CounterTransferRequest) GetAdaptorPublicKeys() *spark.AdaptorPublicKeyPackage {
	if x != nil {
		return x.AdaptorPublicKeys
	}
	return nil
}

func (x *CounterTransferRequest) GetPrimaryTransferId() string {
	if x != nil {
		return x.PrimaryTransferId
	}
	return ""
}

type ReturnStuckTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnStuckTransferRequest) Reset() {
	*x = ReturnStuckTransferRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnStuckTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnStuckTransferRequest) ProtoMessage() {}

func (x *ReturnStuckTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnStuckTransferRequest.ProtoReflect.Descriptor instead.
func (*ReturnStuckTransferRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{3}
}

func (x *ReturnStuckTransferRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type ReturnStuckTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnStuckTransferResponse) Reset() {
	*x = ReturnStuckTransferResponse{}
	mi := &file_spark_ssp_internal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnStuckTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnStuckTransferResponse) ProtoMessage() {}

func (x *ReturnStuckTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnStuckTransferResponse.ProtoReflect.Descriptor instead.
func (*ReturnStuckTransferResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{4}
}

type SweepInput struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OnChainUtxo *spark.UTXO            `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	// Index of this UTXO in the sweep transaction's input list.
	Vin uint32 `protobuf:"varint,2,opt,name=vin,proto3" json:"vin,omitempty"`
	// The SSP's round-1 commitment for this input.
	UserSigningCommitment *common.SigningCommitment `protobuf:"bytes,3,opt,name=user_signing_commitment,json=userSigningCommitment,proto3" json:"user_signing_commitment,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SweepInput) Reset() {
	*x = SweepInput{}
	mi := &file_spark_ssp_internal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SweepInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SweepInput) ProtoMessage() {}

func (x *SweepInput) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SweepInput.ProtoReflect.Descriptor instead.
func (*SweepInput) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{5}
}

func (x *SweepInput) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *SweepInput) GetVin() uint32 {
	if x != nil {
		return x.Vin
	}
	return 0
}

func (x *SweepInput) GetUserSigningCommitment() *common.SigningCommitment {
	if x != nil {
		return x.UserSigningCommitment
	}
	return nil
}

type SignStaticDepositSweepTxRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Network spark.Network          `protobuf:"varint,1,opt,name=network,proto3,enum=spark.Network" json:"network,omitempty"`
	// The sweep transaction, spending every UTXO in inputs.
	RawTx  []byte        `protobuf:"bytes,2,opt,name=raw_tx,json=rawTx,proto3" json:"raw_tx,omitempty"`
	Inputs []*SweepInput `protobuf:"bytes,3,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// The SSP identity key's signature over the sweep statement, which commits to
	// the network and the sweep transaction's txid.
	SspSignature  []byte `protobuf:"bytes,4,opt,name=ssp_signature,json=sspSignature,proto3" json:"ssp_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignStaticDepositSweepTxRequest) Reset() {
	*x = SignStaticDepositSweepTxRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignStaticDepositSweepTxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignStaticDepositSweepTxRequest) ProtoMessage() {}

func (x *SignStaticDepositSweepTxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignStaticDepositSweepTxRequest.ProtoReflect.Descriptor instead.
func (*SignStaticDepositSweepTxRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{6}
}

func (x *SignStaticDepositSweepTxRequest) GetNetwork() spark.Network {
	if x != nil {
		return x.Network
	}
	return spark.Network(0)
}

func (x *SignStaticDepositSweepTxRequest) GetRawTx() []byte {
	if x != nil {
		return x.RawTx
	}
	return nil
}

func (x *SignStaticDepositSweepTxRequest) GetInputs() []*SweepInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *SignStaticDepositSweepTxRequest) GetSspSignature() []byte {
	if x != nil {
		return x.SspSignature
	}
	return nil
}

type SweepInputSigningResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           uint32                 `protobuf:"varint,1,opt,name=vin,proto3" json:"vin,omitempty"`
	SigningResult *spark.SigningResult   `protobuf:"bytes,2,opt,name=signing_result,json=signingResult,proto3" json:"signing_result,omitempty"`
	// The verifying key of the deposit address this input spends from.
	VerifyingKey  []byte `protobuf:"bytes,3,opt,name=verifying_key,json=verifyingKey,proto3" json:"verifying_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SweepInputSigningResult) Reset() {
	*x = SweepInputSigningResult{}
	mi := &file_spark_ssp_internal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SweepInputSigningResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SweepInputSigningResult) ProtoMessage() {}

func (x *SweepInputSigningResult) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SweepInputSigningResult.ProtoReflect.Descriptor instead.
func (*SweepInputSigningResult) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{7}
}

func (x *SweepInputSigningResult) GetVin() uint32 {
	if x != nil {
		return x.Vin
	}
	return 0
}

func (x *SweepInputSigningResult) GetSigningResult() *spark.SigningResult {
	if x != nil {
		return x.SigningResult
	}
	return nil
}

func (x *SweepInputSigningResult) GetVerifyingKey() []byte {
	if x != nil {
		return x.VerifyingKey
	}
	return nil
}

type SweptInputs struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Results       []*SweepInputSigningResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SweptInputs) Reset() {
	*x = SweptInputs{}
	mi := &file_spark_ssp_internal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SweptInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SweptInputs) ProtoMessage() {}

func (x *SweptInputs) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SweptInputs.ProtoReflect.Descriptor instead.
func (*SweptInputs) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{8}
}

func (x *SweptInputs) GetResults() []*SweepInputSigningResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type IneligibleSweepInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnChainUtxo   *spark.UTXO            `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	Reason        SweepIneligibleReason  `protobuf:"varint,2,opt,name=reason,proto3,enum=spark_ssp_internal.SweepIneligibleReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IneligibleSweepInput) Reset() {
	*x = IneligibleSweepInput{}
	mi := &file_spark_ssp_internal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IneligibleSweepInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IneligibleSweepInput) ProtoMessage() {}

func (x *IneligibleSweepInput) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IneligibleSweepInput.ProtoReflect.Descriptor instead.
func (*IneligibleSweepInput) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{9}
}

func (x *IneligibleSweepInput) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *IneligibleSweepInput) GetReason() SweepIneligibleReason {
	if x != nil {
		return x.Reason
	}
	return SweepIneligibleReason_SWEEP_INELIGIBLE_REASON_UNSPECIFIED
}

type IneligibleSweepInputs struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Inputs        []*IneligibleSweepInput `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IneligibleSweepInputs) Reset() {
	*x = IneligibleSweepInputs{}
	mi := &file_spark_ssp_internal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IneligibleSweepInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IneligibleSweepInputs) ProtoMessage() {}

func (x *IneligibleSweepInputs) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IneligibleSweepInputs.ProtoReflect.Descriptor instead.
func (*IneligibleSweepInputs) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{10}
}

func (x *IneligibleSweepInputs) GetInputs() []*IneligibleSweepInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type SignStaticDepositSweepTxResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*SignStaticDepositSweepTxResponse_Signed
	//	*SignStaticDepositSweepTxResponse_Ineligible
	Result        isSignStaticDepositSweepTxResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignStaticDepositSweepTxResponse) Reset() {
	*x = SignStaticDepositSweepTxResponse{}
	mi := &file_spark_ssp_internal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignStaticDepositSweepTxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignStaticDepositSweepTxResponse) ProtoMessage() {}

func (x *SignStaticDepositSweepTxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignStaticDepositSweepTxResponse.ProtoReflect.Descriptor instead.
func (*SignStaticDepositSweepTxResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{11}
}

func (x *SignStaticDepositSweepTxResponse) GetResult() isSignStaticDepositSweepTxResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SignStaticDepositSweepTxResponse) GetSigned() *SweptInputs {
	if x != nil {
		if x, ok := x.Result.(*SignStaticDepositSweepTxResponse_Signed); ok {
			return x.Signed
		}
	}
	return nil
}

func (x *SignStaticDepositSweepTxResponse) GetIneligible() *IneligibleSweepInputs {
	if x != nil {
		if x, ok := x.Result.(*SignStaticDepositSweepTxResponse_Ineligible); ok {
			return x.Ineligible
		}
	}
	return nil
}

type isSignStaticDepositSweepTxResponse_Result interface {
	isSignStaticDepositSweepTxResponse_Result()
}

type SignStaticDepositSweepTxResponse_Signed struct {
	Signed *SweptInputs `protobuf:"bytes,1,opt,name=signed,proto3,oneof"`
}

type SignStaticDepositSweepTxResponse_Ineligible struct {
	Ineligible *IneligibleSweepInputs `protobuf:"bytes,2,opt,name=ineligible,proto3,oneof"`
}

func (*SignStaticDepositSweepTxResponse_Signed) isSignStaticDepositSweepTxResponse_Result() {}

func (*SignStaticDepositSweepTxResponse_Ineligible) isSignStaticDepositSweepTxResponse_Result() {}

// Phase one of the instant (0-conf) static-deposit swap: the SSP asks the SE to credit the
// user a Spark transfer against a deposit UTXO that may still be unconfirmed. The reservation
// stays open until the claim phase sweeps the UTXO once it confirms.
type ReserveInstantStaticDepositUtxoSwapRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OnChainUtxo *spark.UTXO            `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	// SSP signature over the message consenting to credit a specific amount for a specific UTXO.
	SspSignature []byte `protobuf:"bytes,2,opt,name=ssp_signature,json=sspSignature,proto3" json:"ssp_signature,omitempty"`
	// User signature over the message consenting to exchange the UTXO for the SSP's transfer.
	UserSignature []byte `protobuf:"bytes,3,opt,name=user_signature,json=userSignature,proto3" json:"user_signature,omitempty"`
	// Transfer package crediting the user, sent from the SSP.
	Transfer *spark.StartTransferRequest `protobuf:"bytes,4,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// Static deposit address the UTXO was paid to.
	DestinationAddress string `protobuf:"bytes,5,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	// UTXO output value in satoshis.
	ValueSats int64 `protobuf:"varint,6,opt,name=value_sats,json=valueSats,proto3" json:"value_sats,omitempty"`
	// Primary credit amount in satoshis.
	CreditAmountSats int64 `protobuf:"varint,7,opt,name=credit_amount_sats,json=creditAmountSats,proto3" json:"credit_amount_sats,omitempty"`
	// Optional secondary credit amount in satoshis (claimed with a secondary transfer).
	SecondaryCreditAmountSats int64 `protobuf:"varint,8,opt,name=secondary_credit_amount_sats,json=secondaryCreditAmountSats,proto3" json:"secondary_credit_amount_sats,omitempty"`
	// Requested secondary transfer id, required iff secondary_credit_amount_sats is set.
	RequestedSecondaryTransferId string `protobuf:"bytes,10,opt,name=requested_secondary_transfer_id,json=requestedSecondaryTransferId,proto3" json:"requested_secondary_transfer_id,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) Reset() {
	*x = ReserveInstantStaticDepositUtxoSwapRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInstantStaticDepositUtxoSwapRequest) ProtoMessage() {}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInstantStaticDepositUtxoSwapRequest.ProtoReflect.Descriptor instead.
func (*ReserveInstantStaticDepositUtxoSwapRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{12}
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetSspSignature() []byte {
	if x != nil {
		return x.SspSignature
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetUserSignature() []byte {
	if x != nil {
		return x.UserSignature
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetTransfer() *spark.StartTransferRequest {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetValueSats() int64 {
	if x != nil {
		return x.ValueSats
	}
	return 0
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetCreditAmountSats() int64 {
	if x != nil {
		return x.CreditAmountSats
	}
	return 0
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetSecondaryCreditAmountSats() int64 {
	if x != nil {
		return x.SecondaryCreditAmountSats
	}
	return 0
}

func (x *ReserveInstantStaticDepositUtxoSwapRequest) GetRequestedSecondaryTransferId() string {
	if x != nil {
		return x.RequestedSecondaryTransferId
	}
	return ""
}

type ReserveInstantStaticDepositUtxoSwapResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Primary transfer crediting the user, sent at reserve time.
	Transfer *spark.Transfer `protobuf:"bytes,1,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// Reservation handle the claim phase uses to locate this swap.
	UtxoSwapId    string `protobuf:"bytes,2,opt,name=utxo_swap_id,json=utxoSwapId,proto3" json:"utxo_swap_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) Reset() {
	*x = ReserveInstantStaticDepositUtxoSwapResponse{}
	mi := &file_spark_ssp_internal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveInstantStaticDepositUtxoSwapResponse) ProtoMessage() {}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveInstantStaticDepositUtxoSwapResponse.ProtoReflect.Descriptor instead.
func (*ReserveInstantStaticDepositUtxoSwapResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{13}
}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) GetTransfer() *spark.Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ReserveInstantStaticDepositUtxoSwapResponse) GetUtxoSwapId() string {
	if x != nil {
		return x.UtxoSwapId
	}
	return ""
}

// Phase two of the instant static-deposit swap: the reserved UTXO has confirmed, so the SE
// co-signs the SSP's spend transaction and sends any secondary transfer, then completes the swap.
type ClaimInstantStaticDepositUtxoSwapRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OnChainUtxo *spark.UTXO            `protobuf:"bytes,1,opt,name=on_chain_utxo,json=onChainUtxo,proto3" json:"on_chain_utxo,omitempty"`
	// Reservation handle returned by the reserve phase.
	UtxoSwapId string `protobuf:"bytes,2,opt,name=utxo_swap_id,json=utxoSwapId,proto3" json:"utxo_swap_id,omitempty"`
	// Optional secondary transfer package, present iff the reservation has a secondary credit.
	Transfer *spark.StartTransferRequest `protobuf:"bytes,3,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// Transaction the SSP built spending the UTXO to an address it owns.
	SpendTxSigningJob *spark.SigningJob `protobuf:"bytes,4,opt,name=spend_tx_signing_job,json=spendTxSigningJob,proto3" json:"spend_tx_signing_job,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) Reset() {
	*x = ClaimInstantStaticDepositUtxoSwapRequest{}
	mi := &file_spark_ssp_internal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimInstantStaticDepositUtxoSwapRequest) ProtoMessage() {}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimInstantStaticDepositUtxoSwapRequest.ProtoReflect.Descriptor instead.
func (*ClaimInstantStaticDepositUtxoSwapRequest) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{14}
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) GetOnChainUtxo() *spark.UTXO {
	if x != nil {
		return x.OnChainUtxo
	}
	return nil
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) GetUtxoSwapId() string {
	if x != nil {
		return x.UtxoSwapId
	}
	return ""
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) GetTransfer() *spark.StartTransferRequest {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ClaimInstantStaticDepositUtxoSwapRequest) GetSpendTxSigningJob() *spark.SigningJob {
	if x != nil {
		return x.SpendTxSigningJob
	}
	return nil
}

type ClaimInstantStaticDepositUtxoSwapResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SE co-signature over the SSP's spend transaction.
	SpendTxSigningResult *spark.SigningResult `protobuf:"bytes,1,opt,name=spend_tx_signing_result,json=spendTxSigningResult,proto3" json:"spend_tx_signing_result,omitempty"`
	// Secondary transfer, present iff the reservation carried a secondary credit.
	Transfer       *spark.Transfer                  `protobuf:"bytes,2,opt,name=transfer,proto3" json:"transfer,omitempty"`
	DepositAddress *spark.DepositAddressQueryResult `protobuf:"bytes,3,opt,name=deposit_address,json=depositAddress,proto3" json:"deposit_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) Reset() {
	*x = ClaimInstantStaticDepositUtxoSwapResponse{}
	mi := &file_spark_ssp_internal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimInstantStaticDepositUtxoSwapResponse) ProtoMessage() {}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spark_ssp_internal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimInstantStaticDepositUtxoSwapResponse.ProtoReflect.Descriptor instead.
func (*ClaimInstantStaticDepositUtxoSwapResponse) Descriptor() ([]byte, []int) {
	return file_spark_ssp_internal_proto_rawDescGZIP(), []int{15}
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) GetSpendTxSigningResult() *spark.SigningResult {
	if x != nil {
		return x.SpendTxSigningResult
	}
	return nil
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) GetTransfer() *spark.Transfer {
	if x != nil {
		return x.Transfer
	}
	return nil
}

func (x *ClaimInstantStaticDepositUtxoSwapResponse) GetDepositAddress() *spark.DepositAddressQueryResult {
	if x != nil {
		return x.DepositAddress
	}
	return nil
}

var File_spark_ssp_internal_proto protoreflect.FileDescriptor

const file_spark_ssp_internal_proto_rawDesc = "" +
	"\n" +
	"\x18spark_ssp_internal.proto\x12\x12spark_ssp_internal\x1a\fcommon.proto\x1a\vspark.proto\x1a\x17validate/validate.proto\"\xae\x03\n" +
	"$InitiateStaticDepositUtxoSwapRequest\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12#\n" +
	"\rssp_signature\x18\x02 \x01(\fR\fsspSignature\x12%\n" +
	"\x0euser_signature\x18\x03 \x01(\fR\ruserSignature\x127\n" +
	"\btransfer\x18\x04 \x01(\v2\x1b.spark.StartTransferRequestR\btransfer\x12B\n" +
	"\x14spend_tx_signing_job\x18\x05 \x01(\v2\x11.spark.SigningJobR\x11spendTxSigningJob\x125\n" +
	"\fhash_variant\x18\x06 \x01(\x0e2\x12.spark.HashVariantR\vhashVariant\x12:\n" +
	"\x16confirmation_threshold\x18\a \x01(\rH\x00R\x15confirmationThreshold\x88\x01\x01B\x19\n" +
	"\x17_confirmation_threshold\"\xec\x01\n" +
	"%InitiateStaticDepositUtxoSwapResponse\x12K\n" +
	"\x17spend_tx_signing_result\x18\x01 \x01(\v2\x14.spark.SigningResultR\x14spendTxSigningResult\x12+\n" +
	"\btransfer\x18\x02 \x01(\v2\x0f.spark.TransferR\btransfer\x12I\n" +
	"\x0fdeposit_address\x18\x03 \x01(\v2 .spark.DepositAddressQueryResultR\x0edepositAddress\"\xd1\x01\n" +
	"\x16CounterTransferRequest\x127\n" +
	"\btransfer\x18\x01 \x01(\v2\x1b.spark.StartTransferRequestR\btransfer\x12N\n" +
	"\x13adaptor_public_keys\x18\x02 \x01(\v2\x1e.spark.AdaptorPublicKeyPackageR\x11adaptorPublicKeys\x12.\n" +
	"\x13primary_transfer_id\x18\x03 \x01(\tR\x11primaryTransferId\"=\n" +
	"\x1aReturnStuckTransferRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\"\x1d\n" +
	"\x1bReturnStuckTransferResponse\"\xa2\x01\n" +
	"\n" +
	"SweepInput\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12\x10\n" +
	"\x03vin\x18\x02 \x01(\rR\x03vin\x12Q\n" +
	"\x17user_signing_commitment\x18\x03 \x01(\v2\x19.common.SigningCommitmentR\x15userSigningCommitment\"\xcc\x01\n" +
	"\x1fSignStaticDepositSweepTxRequest\x12(\n" +
	"\anetwork\x18\x01 \x01(\x0e2\x0e.spark.NetworkR\anetwork\x12\x15\n" +
	"\x06raw_tx\x18\x02 \x01(\fR\x05rawTx\x12C\n" +
	"\x06inputs\x18\x03 \x03(\v2\x1e.spark_ssp_internal.SweepInputB\v\xfaB\b\x92\x01\x05\b\x01\x10\xc8\x01R\x06inputs\x12#\n" +
	"\rssp_signature\x18\x04 \x01(\fR\fsspSignature\"\x96\x01\n" +
	"\x17SweepInputSigningResult\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\rR\x03vin\x12;\n" +
	"\x0esigning_result\x18\x02 \x01(\v2\x14.spark.SigningResultR\rsigningResult\x12,\n" +
	"\rverifying_key\x18\x03 \x01(\fB\a\xfaB\x04z\x02h!R\fverifyingKey\"T\n" +
	"\vSweptInputs\x12E\n" +
	"\aresults\x18\x01 \x03(\v2+.spark_ssp_internal.SweepInputSigningResultR\aresults\"\x8a\x01\n" +
	"\x14IneligibleSweepInput\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12A\n" +
	"\x06reason\x18\x02 \x01(\x0e2).spark_ssp_internal.SweepIneligibleReasonR\x06reason\"Y\n" +
	"\x15IneligibleSweepInputs\x12@\n" +
	"\x06inputs\x18\x01 \x03(\v2(.spark_ssp_internal.IneligibleSweepInputR\x06inputs\"\xb4\x01\n" +
	" SignStaticDepositSweepTxResponse\x129\n" +
	"\x06signed\x18\x01 \x01(\v2\x1f.spark_ssp_internal.SweptInputsH\x00R\x06signed\x12K\n" +
	"\n" +
	"ineligible\x18\x02 \x01(\v2).spark_ssp_internal.IneligibleSweepInputsH\x00R\n" +
	"ineligibleB\b\n" +
	"\x06result\"\xee\x03\n" +
	"*ReserveInstantStaticDepositUtxoSwapRequest\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12#\n" +
	"\rssp_signature\x18\x02 \x01(\fR\fsspSignature\x12%\n" +
	"\x0euser_signature\x18\x03 \x01(\fR\ruserSignature\x127\n" +
	"\btransfer\x18\x04 \x01(\v2\x1b.spark.StartTransferRequestR\btransfer\x12/\n" +
	"\x13destination_address\x18\x05 \x01(\tR\x12destinationAddress\x12\x1d\n" +
	"\n" +
	"value_sats\x18\x06 \x01(\x03R\tvalueSats\x12,\n" +
	"\x12credit_amount_sats\x18\a \x01(\x03R\x10creditAmountSats\x12?\n" +
	"\x1csecondary_credit_amount_sats\x18\b \x01(\x03R\x19secondaryCreditAmountSats\x12E\n" +
	"\x1frequested_secondary_transfer_id\x18\n" +
	" \x01(\tR\x1crequestedSecondaryTransferIdJ\x04\b\t\x10\n" +
	"\"|\n" +
	"+ReserveInstantStaticDepositUtxoSwapResponse\x12+\n" +
	"\btransfer\x18\x01 \x01(\v2\x0f.spark.TransferR\btransfer\x12 \n" +
	"\futxo_swap_id\x18\x02 \x01(\tR\n" +
	"utxoSwapId\"\xfa\x01\n" +
	"(ClaimInstantStaticDepositUtxoSwapRequest\x12/\n" +
	"\ron_chain_utxo\x18\x01 \x01(\v2\v.spark.UTXOR\vonChainUtxo\x12 \n" +
	"\futxo_swap_id\x18\x02 \x01(\tR\n" +
	"utxoSwapId\x127\n" +
	"\btransfer\x18\x03 \x01(\v2\x1b.spark.StartTransferRequestR\btransfer\x12B\n" +
	"\x14spend_tx_signing_job\x18\x04 \x01(\v2\x11.spark.SigningJobR\x11spendTxSigningJob\"\xf0\x01\n" +
	")ClaimInstantStaticDepositUtxoSwapResponse\x12K\n" +
	"\x17spend_tx_signing_result\x18\x01 \x01(\v2\x14.spark.SigningResultR\x14spendTxSigningResult\x12+\n" +
	"\btransfer\x18\x02 \x01(\v2\x0f.spark.TransferR\btransfer\x12I\n" +
	"\x0fdeposit_address\x18\x03 \x01(\v2 .spark.DepositAddressQueryResultR\x0edepositAddress*\x99\x02\n" +
	"\x15SweepIneligibleReason\x12'\n" +
	"#SWEEP_INELIGIBLE_REASON_UNSPECIFIED\x10\x00\x12(\n" +
	"$SWEEP_INELIGIBLE_REASON_UNKNOWN_UTXO\x10\x01\x12#\n" +
	"\x1fSWEEP_INELIGIBLE_REASON_NO_SWAP\x10\x02\x12.\n" +
	"*SWEEP_INELIGIBLE_REASON_SWAP_NOT_COMPLETED\x10\x03\x12/\n" +
	"+SWEEP_INELIGIBLE_REASON_NOT_OWNED_BY_CALLER\x10\x04\x12'\n" +
	"#SWEEP_INELIGIBLE_REASON_REFUND_SWAP\x10\x052\xa8\b\n" +
	"\x17SparkSspInternalService\x12]\n" +
	"\x14prepare_tree_address\x12 .spark.PrepareTreeAddressRequest\x1a!.spark.PrepareTreeAddressResponse\"\x00\x12D\n" +
	"\vcreate_tree\x12\x18.spark.CreateTreeRequest\x1a\x19.spark.CreateTreeResponse\"\x00\x12g\n" +
	"\x19initiate_counter_transfer\x12*.spark_ssp_internal.CounterTransferRequest\x1a\x1c.spark.StartTransferResponse\"\x00\x12z\n" +
	"\x15return_stuck_transfer\x12..spark_ssp_internal.ReturnStuckTransferRequest\x1a/.spark_ssp_internal.ReturnStuckTransferResponse\"\x00\x12\x9a\x01\n" +
	"!initiate_static_deposit_utxo_swap\x128.spark_ssp_internal.InitiateStaticDepositUtxoSwapRequest\x1a9.spark_ssp_internal.InitiateStaticDepositUtxoSwapResponse\"\x00\x12\xad\x01\n" +
	"(reserve_instant_static_deposit_utxo_swap\x12>.spark_ssp_internal.ReserveInstantStaticDepositUtxoSwapRequest\x1a?.spark_ssp_internal.ReserveInstantStaticDepositUtxoSwapResponse\"\x00\x12\xa7\x01\n" +
	"&claim_instant_static_deposit_utxo_swap\x12<.spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapRequest\x1a=.spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapResponse\"\x00\x12\x8b\x01\n" +
	"\x1csign_static_deposit_sweep_tx\x123.spark_ssp_internal.SignStaticDepositSweepTxRequest\x1a4.spark_ssp_internal.SignStaticDepositSweepTxResponse\"\x00B9Z7github.com/lightsparkdev/spark/proto/spark_ssp_internalb\x06proto3"

var (
	file_spark_ssp_internal_proto_rawDescOnce sync.Once
	file_spark_ssp_internal_proto_rawDescData []byte
)

func file_spark_ssp_internal_proto_rawDescGZIP() []byte {
	file_spark_ssp_internal_proto_rawDescOnce.Do(func() {
		file_spark_ssp_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spark_ssp_internal_proto_rawDesc), len(file_spark_ssp_internal_proto_rawDesc)))
	})
	return file_spark_ssp_internal_proto_rawDescData
}

var file_spark_ssp_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spark_ssp_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_spark_ssp_internal_proto_goTypes = []any{
	(SweepIneligibleReason)(0),                          // 0: spark_ssp_internal.SweepIneligibleReason
	(*InitiateStaticDepositUtxoSwapRequest)(nil),        // 1: spark_ssp_internal.InitiateStaticDepositUtxoSwapRequest
	(*InitiateStaticDepositUtxoSwapResponse)(nil),       // 2: spark_ssp_internal.InitiateStaticDepositUtxoSwapResponse
	(*CounterTransferRequest)(nil),                      // 3: spark_ssp_internal.CounterTransferRequest
	(*ReturnStuckTransferRequest)(nil),                  // 4: spark_ssp_internal.ReturnStuckTransferRequest
	(*ReturnStuckTransferResponse)(nil),                 // 5: spark_ssp_internal.ReturnStuckTransferResponse
	(*SweepInput)(nil),                                  // 6: spark_ssp_internal.SweepInput
	(*SignStaticDepositSweepTxRequest)(nil),             // 7: spark_ssp_internal.SignStaticDepositSweepTxRequest
	(*SweepInputSigningResult)(nil),                     // 8: spark_ssp_internal.SweepInputSigningResult
	(*SweptInputs)(nil),                                 // 9: spark_ssp_internal.SweptInputs
	(*IneligibleSweepInput)(nil),                        // 10: spark_ssp_internal.IneligibleSweepInput
	(*IneligibleSweepInputs)(nil),                       // 11: spark_ssp_internal.IneligibleSweepInputs
	(*SignStaticDepositSweepTxResponse)(nil),            // 12: spark_ssp_internal.SignStaticDepositSweepTxResponse
	(*ReserveInstantStaticDepositUtxoSwapRequest)(nil),  // 13: spark_ssp_internal.ReserveInstantStaticDepositUtxoSwapRequest
	(*ReserveInstantStaticDepositUtxoSwapResponse)(nil), // 14: spark_ssp_internal.ReserveInstantStaticDepositUtxoSwapResponse
	(*ClaimInstantStaticDepositUtxoSwapRequest)(nil),    // 15: spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapRequest
	(*ClaimInstantStaticDepositUtxoSwapResponse)(nil),   // 16: spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapResponse
	(*spark.UTXO)(nil),                                  // 17: spark.UTXO
	(*spark.StartTransferRequest)(nil),                  // 18: spark.StartTransferRequest
	(*spark.SigningJob)(nil),                            // 19: spark.SigningJob
	(spark.HashVariant)(0),                              // 20: spark.HashVariant
	(*spark.SigningResult)(nil),                         // 21: spark.SigningResult
	(*spark.Transfer)(nil),                              // 22: spark.Transfer
	(*spark.DepositAddressQueryResult)(nil),             // 23: spark.DepositAddressQueryResult
	(*spark.AdaptorPublicKeyPackage)(nil),               // 24: spark.AdaptorPublicKeyPackage
	(*common.SigningCommitment)(nil),                    // 25: common.SigningCommitment
	(spark.Network)(0),                                  // 26: spark.Network
	(*spark.PrepareTreeAddressRequest)(nil),             // 27: spark.PrepareTreeAddressRequest
	(*spark.CreateTreeRequest)(nil),                     // 28: spark.CreateTreeRequest
	(*spark.PrepareTreeAddressResponse)(nil),            // 29: spark.PrepareTreeAddressResponse
	(*spark.CreateTreeResponse)(nil),                    // 30: spark.CreateTreeResponse
	(*spark.StartTransferResponse)(nil),                 // 31: spark.StartTransferResponse
}
var file_spark_ssp_internal_proto_depIdxs = []int32{
	17, // 0: spark_ssp_internal.InitiateStaticDepositUtxoSwapRequest.on_chain_utxo:type_name -> spark.UTXO
	18, // 1: spark_ssp_internal.InitiateStaticDepositUtxoSwapRequest.transfer:type_name -> spark.StartTransferRequest
	19, // 2: spark_ssp_internal.InitiateStaticDepositUtxoSwapRequest.spend_tx_signing_job:type_name -> spark.SigningJob
	20, // 3: spark_ssp_internal.InitiateStaticDepositUtxoSwapRequest.hash_variant:type_name -> spark.HashVariant
	21, // 4: spark_ssp_internal.InitiateStaticDepositUtxoSwapResponse.spend_tx_signing_result:type_name -> spark.SigningResult
	22, // 5: spark_ssp_internal.InitiateStaticDepositUtxoSwapResponse.transfer:type_name -> spark.Transfer
	23, // 6: spark_ssp_internal.InitiateStaticDepositUtxoSwapResponse.deposit_address:type_name -> spark.DepositAddressQueryResult
	18, // 7: spark_ssp_internal.CounterTransferRequest.transfer:type_name -> spark.StartTransferRequest
	24, // 8: spark_ssp_internal.CounterTransferRequest.adaptor_public_keys:type_name -> spark.AdaptorPublicKeyPackage
	17, // 9: spark_ssp_internal.SweepInput.on_chain_utxo:type_name -> spark.UTXO
	25, // 10: spark_ssp_internal.SweepInput.user_signing_commitment:type_name -> common.SigningCommitment
	26, // 11: spark_ssp_internal.SignStaticDepositSweepTxRequest.network:type_name -> spark.Network
	6,  // 12: spark_ssp_internal.SignStaticDepositSweepTxRequest.inputs:type_name -> spark_ssp_internal.SweepInput
	21, // 13: spark_ssp_internal.SweepInputSigningResult.signing_result:type_name -> spark.SigningResult
	8,  // 14: spark_ssp_internal.SweptInputs.results:type_name -> spark_ssp_internal.SweepInputSigningResult
	17, // 15: spark_ssp_internal.IneligibleSweepInput.on_chain_utxo:type_name -> spark.UTXO
	0,  // 16: spark_ssp_internal.IneligibleSweepInput.reason:type_name -> spark_ssp_internal.SweepIneligibleReason
	10, // 17: spark_ssp_internal.IneligibleSweepInputs.inputs:type_name -> spark_ssp_internal.IneligibleSweepInput
	9,  // 18: spark_ssp_internal.SignStaticDepositSweepTxResponse.signed:type_name -> spark_ssp_internal.SweptInputs
	11, // 19: spark_ssp_internal.SignStaticDepositSweepTxResponse.ineligible:type_name -> spark_ssp_internal.IneligibleSweepInputs
	17, // 20: spark_ssp_internal.ReserveInstantStaticDepositUtxoSwapRequest.on_chain_utxo:type_name -> spark.UTXO
	18, // 21: spark_ssp_internal.ReserveInstantStaticDepositUtxoSwapRequest.transfer:type_name -> spark.StartTransferRequest
	22, // 22: spark_ssp_internal.ReserveInstantStaticDepositUtxoSwapResponse.transfer:type_name -> spark.Transfer
	17, // 23: spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapRequest.on_chain_utxo:type_name -> spark.UTXO
	18, // 24: spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapRequest.transfer:type_name -> spark.StartTransferRequest
	19, // 25: spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapRequest.spend_tx_signing_job:type_name -> spark.SigningJob
	21, // 26: spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapResponse.spend_tx_signing_result:type_name -> spark.SigningResult
	22, // 27: spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapResponse.transfer:type_name -> spark.Transfer
	23, // 28: spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapResponse.deposit_address:type_name -> spark.DepositAddressQueryResult
	27, // 29: spark_ssp_internal.SparkSspInternalService.prepare_tree_address:input_type -> spark.PrepareTreeAddressRequest
	28, // 30: spark_ssp_internal.SparkSspInternalService.create_tree:input_type -> spark.CreateTreeRequest
	3,  // 31: spark_ssp_internal.SparkSspInternalService.initiate_counter_transfer:input_type -> spark_ssp_internal.CounterTransferRequest
	4,  // 32: spark_ssp_internal.SparkSspInternalService.return_stuck_transfer:input_type -> spark_ssp_internal.ReturnStuckTransferRequest
	1,  // 33: spark_ssp_internal.SparkSspInternalService.initiate_static_deposit_utxo_swap:input_type -> spark_ssp_internal.InitiateStaticDepositUtxoSwapRequest
	13, // 34: spark_ssp_internal.SparkSspInternalService.reserve_instant_static_deposit_utxo_swap:input_type -> spark_ssp_internal.ReserveInstantStaticDepositUtxoSwapRequest
	15, // 35: spark_ssp_internal.SparkSspInternalService.claim_instant_static_deposit_utxo_swap:input_type -> spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapRequest
	7,  // 36: spark_ssp_internal.SparkSspInternalService.sign_static_deposit_sweep_tx:input_type -> spark_ssp_internal.SignStaticDepositSweepTxRequest
	29, // 37: spark_ssp_internal.SparkSspInternalService.prepare_tree_address:output_type -> spark.PrepareTreeAddressResponse
	30, // 38: spark_ssp_internal.SparkSspInternalService.create_tree:output_type -> spark.CreateTreeResponse
	31, // 39: spark_ssp_internal.SparkSspInternalService.initiate_counter_transfer:output_type -> spark.StartTransferResponse
	5,  // 40: spark_ssp_internal.SparkSspInternalService.return_stuck_transfer:output_type -> spark_ssp_internal.ReturnStuckTransferResponse
	2,  // 41: spark_ssp_internal.SparkSspInternalService.initiate_static_deposit_utxo_swap:output_type -> spark_ssp_internal.InitiateStaticDepositUtxoSwapResponse
	14, // 42: spark_ssp_internal.SparkSspInternalService.reserve_instant_static_deposit_utxo_swap:output_type -> spark_ssp_internal.ReserveInstantStaticDepositUtxoSwapResponse
	16, // 43: spark_ssp_internal.SparkSspInternalService.claim_instant_static_deposit_utxo_swap:output_type -> spark_ssp_internal.ClaimInstantStaticDepositUtxoSwapResponse
	12, // 44: spark_ssp_internal.SparkSspInternalService.sign_static_deposit_sweep_tx:output_type -> spark_ssp_internal.SignStaticDepositSweepTxResponse
	37, // [37:45] is the sub-list for method output_type
	29, // [29:37] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_spark_ssp_internal_proto_init() }
func file_spark_ssp_internal_proto_init() {
	if File_spark_ssp_internal_proto != nil {
		return
	}
	file_spark_ssp_internal_proto_msgTypes[0].OneofWrappers = []any{}
	file_spark_ssp_internal_proto_msgTypes[11].OneofWrappers = []any{
		(*SignStaticDepositSweepTxResponse_Signed)(nil),
		(*SignStaticDepositSweepTxResponse_Ineligible)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spark_ssp_internal_proto_rawDesc), len(file_spark_ssp_internal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spark_ssp_internal_proto_goTypes,
		DependencyIndexes: file_spark_ssp_internal_proto_depIdxs,
		EnumInfos:         file_spark_ssp_internal_proto_enumTypes,
		MessageInfos:      file_spark_ssp_internal_proto_msgTypes,
	}.Build()
	File_spark_ssp_internal_proto = out.File
	file_spark_ssp_internal_proto_goTypes = nil
	file_spark_ssp_internal_proto_depIdxs = nil
}
