// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: spark_ssp_internal.proto

package spark_ssp_internal

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"

	spark "github.com/lightsparkdev/spark/proto/spark"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort

	_ = spark.HashVariant(0)
)

// Validate checks the field values on InitiateStaticDepositUtxoSwapRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *InitiateStaticDepositUtxoSwapRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InitiateStaticDepositUtxoSwapRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// InitiateStaticDepositUtxoSwapRequestMultiError, or nil if none found.
func (m *InitiateStaticDepositUtxoSwapRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *InitiateStaticDepositUtxoSwapRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOnChainUtxo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOnChainUtxo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InitiateStaticDepositUtxoSwapRequestValidationError{
				field:  "OnChainUtxo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SspSignature

	// no validation rules for UserSignature

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InitiateStaticDepositUtxoSwapRequestValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSpendTxSigningJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapRequestValidationError{
					field:  "SpendTxSigningJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapRequestValidationError{
					field:  "SpendTxSigningJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpendTxSigningJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InitiateStaticDepositUtxoSwapRequestValidationError{
				field:  "SpendTxSigningJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for HashVariant

	if m.ConfirmationThreshold != nil {
		// no validation rules for ConfirmationThreshold
	}

	if len(errors) > 0 {
		return InitiateStaticDepositUtxoSwapRequestMultiError(errors)
	}

	return nil
}

// InitiateStaticDepositUtxoSwapRequestMultiError is an error wrapping multiple
// validation errors returned by
// InitiateStaticDepositUtxoSwapRequest.ValidateAll() if the designated
// constraints aren't met.
type InitiateStaticDepositUtxoSwapRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InitiateStaticDepositUtxoSwapRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InitiateStaticDepositUtxoSwapRequestMultiError) AllErrors() []error { return m }

// InitiateStaticDepositUtxoSwapRequestValidationError is the validation error
// returned by InitiateStaticDepositUtxoSwapRequest.Validate if the designated
// constraints aren't met.
type InitiateStaticDepositUtxoSwapRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InitiateStaticDepositUtxoSwapRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InitiateStaticDepositUtxoSwapRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InitiateStaticDepositUtxoSwapRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InitiateStaticDepositUtxoSwapRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InitiateStaticDepositUtxoSwapRequestValidationError) ErrorName() string {
	return "InitiateStaticDepositUtxoSwapRequestValidationError"
}

// Error satisfies the builtin error interface
func (e InitiateStaticDepositUtxoSwapRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInitiateStaticDepositUtxoSwapRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InitiateStaticDepositUtxoSwapRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InitiateStaticDepositUtxoSwapRequestValidationError{}

// Validate checks the field values on InitiateStaticDepositUtxoSwapResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *InitiateStaticDepositUtxoSwapResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on InitiateStaticDepositUtxoSwapResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// InitiateStaticDepositUtxoSwapResponseMultiError, or nil if none found.
func (m *InitiateStaticDepositUtxoSwapResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *InitiateStaticDepositUtxoSwapResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSpendTxSigningResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapResponseValidationError{
					field:  "SpendTxSigningResult",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapResponseValidationError{
					field:  "SpendTxSigningResult",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpendTxSigningResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InitiateStaticDepositUtxoSwapResponseValidationError{
				field:  "SpendTxSigningResult",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InitiateStaticDepositUtxoSwapResponseValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDepositAddress()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapResponseValidationError{
					field:  "DepositAddress",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, InitiateStaticDepositUtxoSwapResponseValidationError{
					field:  "DepositAddress",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDepositAddress()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InitiateStaticDepositUtxoSwapResponseValidationError{
				field:  "DepositAddress",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return InitiateStaticDepositUtxoSwapResponseMultiError(errors)
	}

	return nil
}

// InitiateStaticDepositUtxoSwapResponseMultiError is an error wrapping
// multiple validation errors returned by
// InitiateStaticDepositUtxoSwapResponse.ValidateAll() if the designated
// constraints aren't met.
type InitiateStaticDepositUtxoSwapResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m InitiateStaticDepositUtxoSwapResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m InitiateStaticDepositUtxoSwapResponseMultiError) AllErrors() []error { return m }

// InitiateStaticDepositUtxoSwapResponseValidationError is the validation error
// returned by InitiateStaticDepositUtxoSwapResponse.Validate if the
// designated constraints aren't met.
type InitiateStaticDepositUtxoSwapResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InitiateStaticDepositUtxoSwapResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InitiateStaticDepositUtxoSwapResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InitiateStaticDepositUtxoSwapResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InitiateStaticDepositUtxoSwapResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InitiateStaticDepositUtxoSwapResponseValidationError) ErrorName() string {
	return "InitiateStaticDepositUtxoSwapResponseValidationError"
}

// Error satisfies the builtin error interface
func (e InitiateStaticDepositUtxoSwapResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInitiateStaticDepositUtxoSwapResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InitiateStaticDepositUtxoSwapResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InitiateStaticDepositUtxoSwapResponseValidationError{}

// Validate checks the field values on CounterTransferRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CounterTransferRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CounterTransferRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CounterTransferRequestMultiError, or nil if none found.
func (m *CounterTransferRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CounterTransferRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CounterTransferRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CounterTransferRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CounterTransferRequestValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetAdaptorPublicKeys()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CounterTransferRequestValidationError{
					field:  "AdaptorPublicKeys",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CounterTransferRequestValidationError{
					field:  "AdaptorPublicKeys",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAdaptorPublicKeys()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CounterTransferRequestValidationError{
				field:  "AdaptorPublicKeys",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PrimaryTransferId

	if len(errors) > 0 {
		return CounterTransferRequestMultiError(errors)
	}

	return nil
}

// CounterTransferRequestMultiError is an error wrapping multiple validation
// errors returned by CounterTransferRequest.ValidateAll() if the designated
// constraints aren't met.
type CounterTransferRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CounterTransferRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CounterTransferRequestMultiError) AllErrors() []error { return m }

// CounterTransferRequestValidationError is the validation error returned by
// CounterTransferRequest.Validate if the designated constraints aren't met.
type CounterTransferRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CounterTransferRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CounterTransferRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CounterTransferRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CounterTransferRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CounterTransferRequestValidationError) ErrorName() string {
	return "CounterTransferRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CounterTransferRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCounterTransferRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CounterTransferRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CounterTransferRequestValidationError{}

// Validate checks the field values on ReturnStuckTransferRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReturnStuckTransferRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReturnStuckTransferRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReturnStuckTransferRequestMultiError, or nil if none found.
func (m *ReturnStuckTransferRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReturnStuckTransferRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TransferId

	if len(errors) > 0 {
		return ReturnStuckTransferRequestMultiError(errors)
	}

	return nil
}

// ReturnStuckTransferRequestMultiError is an error wrapping multiple
// validation errors returned by ReturnStuckTransferRequest.ValidateAll() if
// the designated constraints aren't met.
type ReturnStuckTransferRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReturnStuckTransferRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReturnStuckTransferRequestMultiError) AllErrors() []error { return m }

// ReturnStuckTransferRequestValidationError is the validation error returned
// by ReturnStuckTransferRequest.Validate if the designated constraints aren't met.
type ReturnStuckTransferRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReturnStuckTransferRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReturnStuckTransferRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReturnStuckTransferRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReturnStuckTransferRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReturnStuckTransferRequestValidationError) ErrorName() string {
	return "ReturnStuckTransferRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReturnStuckTransferRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReturnStuckTransferRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReturnStuckTransferRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReturnStuckTransferRequestValidationError{}

// Validate checks the field values on ReturnStuckTransferResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ReturnStuckTransferResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReturnStuckTransferResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ReturnStuckTransferResponseMultiError, or nil if none found.
func (m *ReturnStuckTransferResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReturnStuckTransferResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ReturnStuckTransferResponseMultiError(errors)
	}

	return nil
}

// ReturnStuckTransferResponseMultiError is an error wrapping multiple
// validation errors returned by ReturnStuckTransferResponse.ValidateAll() if
// the designated constraints aren't met.
type ReturnStuckTransferResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReturnStuckTransferResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReturnStuckTransferResponseMultiError) AllErrors() []error { return m }

// ReturnStuckTransferResponseValidationError is the validation error returned
// by ReturnStuckTransferResponse.Validate if the designated constraints
// aren't met.
type ReturnStuckTransferResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReturnStuckTransferResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReturnStuckTransferResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReturnStuckTransferResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReturnStuckTransferResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReturnStuckTransferResponseValidationError) ErrorName() string {
	return "ReturnStuckTransferResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReturnStuckTransferResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReturnStuckTransferResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReturnStuckTransferResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReturnStuckTransferResponseValidationError{}

// Validate checks the field values on SweepInput with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SweepInput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SweepInput with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SweepInputMultiError, or
// nil if none found.
func (m *SweepInput) ValidateAll() error {
	return m.validate(true)
}

func (m *SweepInput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOnChainUtxo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SweepInputValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SweepInputValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOnChainUtxo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SweepInputValidationError{
				field:  "OnChainUtxo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Vin

	if all {
		switch v := interface{}(m.GetUserSigningCommitment()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SweepInputValidationError{
					field:  "UserSigningCommitment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SweepInputValidationError{
					field:  "UserSigningCommitment",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserSigningCommitment()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SweepInputValidationError{
				field:  "UserSigningCommitment",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SweepInputMultiError(errors)
	}

	return nil
}

// SweepInputMultiError is an error wrapping multiple validation errors
// returned by SweepInput.ValidateAll() if the designated constraints aren't met.
type SweepInputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SweepInputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SweepInputMultiError) AllErrors() []error { return m }

// SweepInputValidationError is the validation error returned by
// SweepInput.Validate if the designated constraints aren't met.
type SweepInputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SweepInputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SweepInputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SweepInputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SweepInputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SweepInputValidationError) ErrorName() string { return "SweepInputValidationError" }

// Error satisfies the builtin error interface
func (e SweepInputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSweepInput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SweepInputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SweepInputValidationError{}

// Validate checks the field values on SignStaticDepositSweepTxRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SignStaticDepositSweepTxRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SignStaticDepositSweepTxRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SignStaticDepositSweepTxRequestMultiError, or nil if none found.
func (m *SignStaticDepositSweepTxRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SignStaticDepositSweepTxRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Network

	// no validation rules for RawTx

	if l := len(m.GetInputs()); l < 1 || l > 200 {
		err := SignStaticDepositSweepTxRequestValidationError{
			field:  "Inputs",
			reason: "value must contain between 1 and 200 items, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	for idx, item := range m.GetInputs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SignStaticDepositSweepTxRequestValidationError{
						field:  fmt.Sprintf("Inputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SignStaticDepositSweepTxRequestValidationError{
						field:  fmt.Sprintf("Inputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SignStaticDepositSweepTxRequestValidationError{
					field:  fmt.Sprintf("Inputs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for SspSignature

	if len(errors) > 0 {
		return SignStaticDepositSweepTxRequestMultiError(errors)
	}

	return nil
}

// SignStaticDepositSweepTxRequestMultiError is an error wrapping multiple
// validation errors returned by SignStaticDepositSweepTxRequest.ValidateAll()
// if the designated constraints aren't met.
type SignStaticDepositSweepTxRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SignStaticDepositSweepTxRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SignStaticDepositSweepTxRequestMultiError) AllErrors() []error { return m }

// SignStaticDepositSweepTxRequestValidationError is the validation error
// returned by SignStaticDepositSweepTxRequest.Validate if the designated
// constraints aren't met.
type SignStaticDepositSweepTxRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SignStaticDepositSweepTxRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SignStaticDepositSweepTxRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SignStaticDepositSweepTxRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SignStaticDepositSweepTxRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SignStaticDepositSweepTxRequestValidationError) ErrorName() string {
	return "SignStaticDepositSweepTxRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SignStaticDepositSweepTxRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSignStaticDepositSweepTxRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SignStaticDepositSweepTxRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SignStaticDepositSweepTxRequestValidationError{}

// Validate checks the field values on SweepInputSigningResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SweepInputSigningResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SweepInputSigningResult with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SweepInputSigningResultMultiError, or nil if none found.
func (m *SweepInputSigningResult) ValidateAll() error {
	return m.validate(true)
}

func (m *SweepInputSigningResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Vin

	if all {
		switch v := interface{}(m.GetSigningResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SweepInputSigningResultValidationError{
					field:  "SigningResult",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SweepInputSigningResultValidationError{
					field:  "SigningResult",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSigningResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SweepInputSigningResultValidationError{
				field:  "SigningResult",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(m.GetVerifyingKey()) != 33 {
		err := SweepInputSigningResultValidationError{
			field:  "VerifyingKey",
			reason: "value length must be 33 bytes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return SweepInputSigningResultMultiError(errors)
	}

	return nil
}

// SweepInputSigningResultMultiError is an error wrapping multiple validation
// errors returned by SweepInputSigningResult.ValidateAll() if the designated
// constraints aren't met.
type SweepInputSigningResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SweepInputSigningResultMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SweepInputSigningResultMultiError) AllErrors() []error { return m }

// SweepInputSigningResultValidationError is the validation error returned by
// SweepInputSigningResult.Validate if the designated constraints aren't met.
type SweepInputSigningResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SweepInputSigningResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SweepInputSigningResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SweepInputSigningResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SweepInputSigningResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SweepInputSigningResultValidationError) ErrorName() string {
	return "SweepInputSigningResultValidationError"
}

// Error satisfies the builtin error interface
func (e SweepInputSigningResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSweepInputSigningResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SweepInputSigningResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SweepInputSigningResultValidationError{}

// Validate checks the field values on SweptInputs with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SweptInputs) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SweptInputs with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SweptInputsMultiError, or
// nil if none found.
func (m *SweptInputs) ValidateAll() error {
	return m.validate(true)
}

func (m *SweptInputs) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SweptInputsValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SweptInputsValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SweptInputsValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SweptInputsMultiError(errors)
	}

	return nil
}

// SweptInputsMultiError is an error wrapping multiple validation errors
// returned by SweptInputs.ValidateAll() if the designated constraints aren't met.
type SweptInputsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SweptInputsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SweptInputsMultiError) AllErrors() []error { return m }

// SweptInputsValidationError is the validation error returned by
// SweptInputs.Validate if the designated constraints aren't met.
type SweptInputsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SweptInputsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SweptInputsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SweptInputsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SweptInputsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SweptInputsValidationError) ErrorName() string { return "SweptInputsValidationError" }

// Error satisfies the builtin error interface
func (e SweptInputsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSweptInputs.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SweptInputsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SweptInputsValidationError{}

// Validate checks the field values on IneligibleSweepInput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IneligibleSweepInput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IneligibleSweepInput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IneligibleSweepInputMultiError, or nil if none found.
func (m *IneligibleSweepInput) ValidateAll() error {
	return m.validate(true)
}

func (m *IneligibleSweepInput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOnChainUtxo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, IneligibleSweepInputValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, IneligibleSweepInputValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOnChainUtxo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return IneligibleSweepInputValidationError{
				field:  "OnChainUtxo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Reason

	if len(errors) > 0 {
		return IneligibleSweepInputMultiError(errors)
	}

	return nil
}

// IneligibleSweepInputMultiError is an error wrapping multiple validation
// errors returned by IneligibleSweepInput.ValidateAll() if the designated
// constraints aren't met.
type IneligibleSweepInputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IneligibleSweepInputMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IneligibleSweepInputMultiError) AllErrors() []error { return m }

// IneligibleSweepInputValidationError is the validation error returned by
// IneligibleSweepInput.Validate if the designated constraints aren't met.
type IneligibleSweepInputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IneligibleSweepInputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IneligibleSweepInputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IneligibleSweepInputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IneligibleSweepInputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IneligibleSweepInputValidationError) ErrorName() string {
	return "IneligibleSweepInputValidationError"
}

// Error satisfies the builtin error interface
func (e IneligibleSweepInputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIneligibleSweepInput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IneligibleSweepInputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IneligibleSweepInputValidationError{}

// Validate checks the field values on IneligibleSweepInputs with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *IneligibleSweepInputs) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on IneligibleSweepInputs with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// IneligibleSweepInputsMultiError, or nil if none found.
func (m *IneligibleSweepInputs) ValidateAll() error {
	return m.validate(true)
}

func (m *IneligibleSweepInputs) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetInputs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, IneligibleSweepInputsValidationError{
						field:  fmt.Sprintf("Inputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, IneligibleSweepInputsValidationError{
						field:  fmt.Sprintf("Inputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return IneligibleSweepInputsValidationError{
					field:  fmt.Sprintf("Inputs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return IneligibleSweepInputsMultiError(errors)
	}

	return nil
}

// IneligibleSweepInputsMultiError is an error wrapping multiple validation
// errors returned by IneligibleSweepInputs.ValidateAll() if the designated
// constraints aren't met.
type IneligibleSweepInputsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m IneligibleSweepInputsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m IneligibleSweepInputsMultiError) AllErrors() []error { return m }

// IneligibleSweepInputsValidationError is the validation error returned by
// IneligibleSweepInputs.Validate if the designated constraints aren't met.
type IneligibleSweepInputsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e IneligibleSweepInputsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e IneligibleSweepInputsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e IneligibleSweepInputsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e IneligibleSweepInputsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e IneligibleSweepInputsValidationError) ErrorName() string {
	return "IneligibleSweepInputsValidationError"
}

// Error satisfies the builtin error interface
func (e IneligibleSweepInputsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sIneligibleSweepInputs.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = IneligibleSweepInputsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = IneligibleSweepInputsValidationError{}

// Validate checks the field values on SignStaticDepositSweepTxResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *SignStaticDepositSweepTxResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SignStaticDepositSweepTxResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SignStaticDepositSweepTxResponseMultiError, or nil if none found.
func (m *SignStaticDepositSweepTxResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *SignStaticDepositSweepTxResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Result.(type) {
	case *SignStaticDepositSweepTxResponse_Signed:
		if v == nil {
			err := SignStaticDepositSweepTxResponseValidationError{
				field:  "Result",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetSigned()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SignStaticDepositSweepTxResponseValidationError{
						field:  "Signed",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SignStaticDepositSweepTxResponseValidationError{
						field:  "Signed",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSigned()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SignStaticDepositSweepTxResponseValidationError{
					field:  "Signed",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *SignStaticDepositSweepTxResponse_Ineligible:
		if v == nil {
			err := SignStaticDepositSweepTxResponseValidationError{
				field:  "Result",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetIneligible()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SignStaticDepositSweepTxResponseValidationError{
						field:  "Ineligible",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SignStaticDepositSweepTxResponseValidationError{
						field:  "Ineligible",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetIneligible()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SignStaticDepositSweepTxResponseValidationError{
					field:  "Ineligible",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return SignStaticDepositSweepTxResponseMultiError(errors)
	}

	return nil
}

// SignStaticDepositSweepTxResponseMultiError is an error wrapping multiple
// validation errors returned by
// SignStaticDepositSweepTxResponse.ValidateAll() if the designated
// constraints aren't met.
type SignStaticDepositSweepTxResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SignStaticDepositSweepTxResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SignStaticDepositSweepTxResponseMultiError) AllErrors() []error { return m }

// SignStaticDepositSweepTxResponseValidationError is the validation error
// returned by SignStaticDepositSweepTxResponse.Validate if the designated
// constraints aren't met.
type SignStaticDepositSweepTxResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SignStaticDepositSweepTxResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SignStaticDepositSweepTxResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SignStaticDepositSweepTxResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SignStaticDepositSweepTxResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SignStaticDepositSweepTxResponseValidationError) ErrorName() string {
	return "SignStaticDepositSweepTxResponseValidationError"
}

// Error satisfies the builtin error interface
func (e SignStaticDepositSweepTxResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSignStaticDepositSweepTxResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SignStaticDepositSweepTxResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SignStaticDepositSweepTxResponseValidationError{}

// Validate checks the field values on
// ReserveInstantStaticDepositUtxoSwapRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReserveInstantStaticDepositUtxoSwapRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ReserveInstantStaticDepositUtxoSwapRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ReserveInstantStaticDepositUtxoSwapRequestMultiError, or nil if none found.
func (m *ReserveInstantStaticDepositUtxoSwapRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReserveInstantStaticDepositUtxoSwapRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOnChainUtxo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOnChainUtxo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReserveInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "OnChainUtxo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for SspSignature

	// no validation rules for UserSignature

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReserveInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for DestinationAddress

	// no validation rules for ValueSats

	// no validation rules for CreditAmountSats

	// no validation rules for SecondaryCreditAmountSats

	// no validation rules for RequestedSecondaryTransferId

	if len(errors) > 0 {
		return ReserveInstantStaticDepositUtxoSwapRequestMultiError(errors)
	}

	return nil
}

// ReserveInstantStaticDepositUtxoSwapRequestMultiError is an error wrapping
// multiple validation errors returned by
// ReserveInstantStaticDepositUtxoSwapRequest.ValidateAll() if the designated
// constraints aren't met.
type ReserveInstantStaticDepositUtxoSwapRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReserveInstantStaticDepositUtxoSwapRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReserveInstantStaticDepositUtxoSwapRequestMultiError) AllErrors() []error { return m }

// ReserveInstantStaticDepositUtxoSwapRequestValidationError is the validation
// error returned by ReserveInstantStaticDepositUtxoSwapRequest.Validate if
// the designated constraints aren't met.
type ReserveInstantStaticDepositUtxoSwapRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) ErrorName() string {
	return "ReserveInstantStaticDepositUtxoSwapRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ReserveInstantStaticDepositUtxoSwapRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReserveInstantStaticDepositUtxoSwapRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReserveInstantStaticDepositUtxoSwapRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReserveInstantStaticDepositUtxoSwapRequestValidationError{}

// Validate checks the field values on
// ReserveInstantStaticDepositUtxoSwapResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReserveInstantStaticDepositUtxoSwapResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ReserveInstantStaticDepositUtxoSwapResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ReserveInstantStaticDepositUtxoSwapResponseMultiError, or nil if none found.
func (m *ReserveInstantStaticDepositUtxoSwapResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReserveInstantStaticDepositUtxoSwapResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ReserveInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ReserveInstantStaticDepositUtxoSwapResponseValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UtxoSwapId

	if len(errors) > 0 {
		return ReserveInstantStaticDepositUtxoSwapResponseMultiError(errors)
	}

	return nil
}

// ReserveInstantStaticDepositUtxoSwapResponseMultiError is an error wrapping
// multiple validation errors returned by
// ReserveInstantStaticDepositUtxoSwapResponse.ValidateAll() if the designated
// constraints aren't met.
type ReserveInstantStaticDepositUtxoSwapResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReserveInstantStaticDepositUtxoSwapResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReserveInstantStaticDepositUtxoSwapResponseMultiError) AllErrors() []error { return m }

// ReserveInstantStaticDepositUtxoSwapResponseValidationError is the validation
// error returned by ReserveInstantStaticDepositUtxoSwapResponse.Validate if
// the designated constraints aren't met.
type ReserveInstantStaticDepositUtxoSwapResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) ErrorName() string {
	return "ReserveInstantStaticDepositUtxoSwapResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ReserveInstantStaticDepositUtxoSwapResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReserveInstantStaticDepositUtxoSwapResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReserveInstantStaticDepositUtxoSwapResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReserveInstantStaticDepositUtxoSwapResponseValidationError{}

// Validate checks the field values on ClaimInstantStaticDepositUtxoSwapRequest
// with the rules defined in the proto definition for this message. If any
// rules are violated, the first error encountered is returned, or nil if
// there are no violations.
func (m *ClaimInstantStaticDepositUtxoSwapRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ClaimInstantStaticDepositUtxoSwapRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ClaimInstantStaticDepositUtxoSwapRequestMultiError, or nil if none found.
func (m *ClaimInstantStaticDepositUtxoSwapRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ClaimInstantStaticDepositUtxoSwapRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetOnChainUtxo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "OnChainUtxo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetOnChainUtxo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "OnChainUtxo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for UtxoSwapId

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSpendTxSigningJob()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "SpendTxSigningJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapRequestValidationError{
					field:  "SpendTxSigningJob",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpendTxSigningJob()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapRequestValidationError{
				field:  "SpendTxSigningJob",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ClaimInstantStaticDepositUtxoSwapRequestMultiError(errors)
	}

	return nil
}

// ClaimInstantStaticDepositUtxoSwapRequestMultiError is an error wrapping
// multiple validation errors returned by
// ClaimInstantStaticDepositUtxoSwapRequest.ValidateAll() if the designated
// constraints aren't met.
type ClaimInstantStaticDepositUtxoSwapRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClaimInstantStaticDepositUtxoSwapRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClaimInstantStaticDepositUtxoSwapRequestMultiError) AllErrors() []error { return m }

// ClaimInstantStaticDepositUtxoSwapRequestValidationError is the validation
// error returned by ClaimInstantStaticDepositUtxoSwapRequest.Validate if the
// designated constraints aren't met.
type ClaimInstantStaticDepositUtxoSwapRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) ErrorName() string {
	return "ClaimInstantStaticDepositUtxoSwapRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ClaimInstantStaticDepositUtxoSwapRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClaimInstantStaticDepositUtxoSwapRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClaimInstantStaticDepositUtxoSwapRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClaimInstantStaticDepositUtxoSwapRequestValidationError{}

// Validate checks the field values on
// ClaimInstantStaticDepositUtxoSwapResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ClaimInstantStaticDepositUtxoSwapResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on
// ClaimInstantStaticDepositUtxoSwapResponse with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in
// ClaimInstantStaticDepositUtxoSwapResponseMultiError, or nil if none found.
func (m *ClaimInstantStaticDepositUtxoSwapResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ClaimInstantStaticDepositUtxoSwapResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetSpendTxSigningResult()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "SpendTxSigningResult",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "SpendTxSigningResult",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpendTxSigningResult()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapResponseValidationError{
				field:  "SpendTxSigningResult",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetTransfer()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "Transfer",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTransfer()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapResponseValidationError{
				field:  "Transfer",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDepositAddress()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "DepositAddress",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ClaimInstantStaticDepositUtxoSwapResponseValidationError{
					field:  "DepositAddress",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDepositAddress()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ClaimInstantStaticDepositUtxoSwapResponseValidationError{
				field:  "DepositAddress",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ClaimInstantStaticDepositUtxoSwapResponseMultiError(errors)
	}

	return nil
}

// ClaimInstantStaticDepositUtxoSwapResponseMultiError is an error wrapping
// multiple validation errors returned by
// ClaimInstantStaticDepositUtxoSwapResponse.ValidateAll() if the designated
// constraints aren't met.
type ClaimInstantStaticDepositUtxoSwapResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ClaimInstantStaticDepositUtxoSwapResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ClaimInstantStaticDepositUtxoSwapResponseMultiError) AllErrors() []error { return m }

// ClaimInstantStaticDepositUtxoSwapResponseValidationError is the validation
// error returned by ClaimInstantStaticDepositUtxoSwapResponse.Validate if the
// designated constraints aren't met.
type ClaimInstantStaticDepositUtxoSwapResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) ErrorName() string {
	return "ClaimInstantStaticDepositUtxoSwapResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ClaimInstantStaticDepositUtxoSwapResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sClaimInstantStaticDepositUtxoSwapResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ClaimInstantStaticDepositUtxoSwapResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ClaimInstantStaticDepositUtxoSwapResponseValidationError{}
